# Generated by Django 4.0.4 on 2022-09-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бригадир',
                'verbose_name_plural': 'Бригадиры',
            },
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('lunch', models.IntegerField(blank=True, default=0, null=True, verbose_name='Обед')),
                ('dinner', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ужин')),
                ('late_dinner', models.IntegerField(blank=True, default=0, null=True, verbose_name='Поздный ужин')),
                ('is_active', models.IntegerField(choices=[('1', 'Активный'), ('2', 'Неактивный'), ('3', 'Удаленный')], default='1')),
                ('brigadir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.brigadir')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.objects')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
