# Generated by Django 4.1.1 on 2022-09-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brigadir',
            options={'verbose_name': 'Бригадир', 'verbose_name_plural': 'Бригадиры'},
        ),
        migrations.AlterModelOptions(
            name='objects',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
    ]
