# Generated by Django 4.0.4 on 2022-09-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Неактивный'), (3, 'Удаленный')], default='1'),
        ),
    ]
