# Generated by Django 4.0.4 on 2022-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_requests_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigadir',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Неактивный'), (3, 'Удаленный')], default='1'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Неактивный'), (3, 'Удаленный')], default='1'),
        ),
    ]
