# Generated by Django 4.1.1 on 2022-09-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_brigadir_options_alter_objects_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('types', models.CharField(choices=[('1', 'Обед'), ('2', 'ужин'), ('3', 'Позд ужин')], max_length=15)),
                ('count', models.IntegerField()),
                ('brigadir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.brigadir')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.objects')),
            ],
        ),
    ]
