# Generated by Django 4.1.1 on 2022-09-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_requests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='requests',
            name='count',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='types',
        ),
        migrations.AddField(
            model_name='requests',
            name='dinner',
            field=models.IntegerField(default=1, verbose_name='Ужин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='late_dinner',
            field=models.IntegerField(default=1, verbose_name='Поздный ужин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requests',
            name='lunch',
            field=models.IntegerField(default=1, verbose_name='Обед'),
            preserve_default=False,
        ),
    ]
