# Generated by Django 4.0.4 on 2022-09-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_brigadir_is_active_alter_objects_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brigadir',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (3, 'Удаленный')], default='1', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='brigadir',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ф.И.О. Бригадира'),
        ),
        migrations.AlterField(
            model_name='brigadir',
            name='phone',
            field=models.CharField(max_length=9, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (3, 'Удаленный')], default='1', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название объекта'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='brigadir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.brigadir', verbose_name='Бригадир'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (3, 'Удаленный')], default='1', verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.objects', verbose_name='Объект'),
        ),
    ]
