# Generated by Django 4.0.4 on 2022-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_requests_dinner_alter_requests_late_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigadir',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
