# Generated by Django 4.0.4 on 2022-09-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_objects_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='brigadir',
        ),
    ]
